version: '3'
services:
 apache:
  build: ./php-apache
  ports:
   - '80:80'
   - '443:443'
  volumes:
   - ./htdocs:/var/www/html   
  links:
   - mysql
  depends_on:
   - mysql  
  container_name: apache 
 mysql:
  build: ./mysql
  ports: 
   - "3306:3306"  
  environment:
   MYSQL_DATABASE: test
   MYSQL_USER: user
   MYSQL_PASSWORD: pass
   MYSQL_ROOT_PASSWORD: pass
  volumes:
   - ./mysql/data:/var/lib/mysql
   - ./mysql/init:/docker-entrypoint-initdb.d
  container_name: mysql   
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: mysql
   PMA_USER: root
   PMA_PASSWORD: pass
  restart: always
  ports:
   - 8080:80
  volumes:
   - /sessions
  links:
   - mysql:mysql